/**
 * 权限配置
 */
module.exports = {
    name: '所有权限',
    description: '所有权限',
    code: 10000,
    id: 10000,
    authorities: [{
            name: '用户管理',
            description: '用户管理',
            code: 100100,
            id: 100100,
            authorities: [{
                name: '查看',
                description: '查看用户',
                code: [100104, 100105],
                id: 100104
            }, {
                name: '编辑',
                description: '编辑用户',
                code: [100103, 100108],
                id: 100103
            }, {
                name: '删除',
                description: '删除用户',
                code: [100102],
                id: 100102
            }, {
                name: '新增',
                description: '新增用户',
                code: [100101],
                id: 100101
            }]
        }, {
            name: '后台用户管理',
            description: '后台用户管理',
            code: 100000,
            id: 100000,
            authorities: [{
                    name: '新增',
                    description: '新增后台用户',
                    code: [100001],
                    id: 100001
                }, {
                    name: '删除',
                    description: '删除',
                    code: [100002],
                    id: 100002
                }, {
                    name: '编辑',
                    description: '编辑',
                    code: [100003],
                    id: 100003
                }, {
                    name: '查看',
                    description: '查看',
                    code: [100004, 100005, 100006],
                    id: 100004
                }

            ]
        }, {
            name: '权限管理',
            description: '权限组管理',
            code: 100200,
            id: 100200,
            authorities: [{
                name: '新增',
                description: '新增权限组',
                code: [100201],
                id: 100201
            }, {
                name: '删除',
                description: '删除权限组',
                code: [100202],
                id: 100202
            }, {
                name: '编辑',
                description: '编辑权限组',
                code: [100203],
                id: 100203
            }, {
                name: '查看',
                description: '查看权限组',
                code: [100204, 100205],
                id: 100204
            }]
        }, {
            name: '经络仪管理',
            description: '经络仪管理',
            code: 100300,
            id: 100300,
            authorities: [{
                name: '新增',
                description: '新增经络仪',
                code: [100301],
                id: 100301
            }, {
                name: '删除',
                description: '删除经络仪',
                code: [100302],
                id: 100302
            }, {
                name: '编辑',
                description: '编辑经络仪',
                code: [100303, 100306],
                id: 100303
            }, {
                name: '查看',
                description: '查看经络仪',
                code: [100304, 100305, 100307],
                id: 100304
            }]
        }, {
            name: '店铺管理',
            description: '店铺管理',
            code: 100400,
            id: 100400,
            authorities: [{
                name: '新增',
                description: '新增店铺',
                code: [100401],
                id: 100401
            }, {
                name: '删除',
                description: '删除店铺',
                code: [100402],
                id: 100402
            }, {
                name: '编辑',
                description: '编辑店铺',
                code: [100403],
                id: 100403
            }, {
                name: '查看',
                description: '查看店铺',
                code: [100404, 100405],
                id: 100404
            }]
        }, {
            name: '广告管理',
            description: '广告管理',
            code: 100600,
            id: 100600,
            authorities: [{
                name: '新增',
                description: '新增广告',
                code: [100601],
                id: 100601
            }, {
                name: '查看',
                description: '查看广告',
                code: [100602, 100603],
                id: 100602
            }, {
                name: '编辑',
                description: '编辑广告',
                code: [100604],
                id: 100604
            }, {
                name: '删除',
                description: '删除广告',
                code: [100605],
                id: 100605
            }, ]
        }, {
            name: '专家案例管理',
            description: '专家案例管理',
            code: 100700,
            id: 100700,
            authorities: [{
                name: '新增',
                description: '新增案例',
                code: [100701],
                id: 100701
            }, {
                name: '查看',
                description: '查看案例',
                code: [100702, 100703],
                id: 100702
            }, {
                name: '编辑',
                description: '编辑案例',
                code: [100704, 100705],
                id: 100704
            }, {
                name: '删除',
                description: '删除案例',
                code: [100706, 100707],
                id: 100706
            }, ]
        }, {
            name: '问诊单管理',
            description: '问诊单管理',
            code: 100800,
            id: 100800,
            authorities: [{
                name: '新增',
                description: '新增问诊单',
                code: [100801],
                id: 100801
            }, {
                name: '查看',
                description: '查看问诊单',
                code: [100802, 100803],
                id: 100802
            }, {
                name: '编辑',
                description: '编辑问诊单',
                code: [100804],
                id: 100804
            }, {
                name: '删除',
                description: '删除问诊单',
                code: [100805, 100810],
                id: 100805
            }, ]
        }, {
            name: '问题管理',
            description: '问题管理',
            code: 102500,
            id: 102500,
            authorities: [{
                name: '新增',
                description: '新增问题',
                code: [102501],
                id: 102501
            }, {
                name: '查看',
                description: '查看问题',
                code: [102502, 102503],
                id: 102502
            }, {
                name: '编辑',
                description: '编辑问题',
                code: [102504],
                id: 102504
            }, {
                name: '删除',
                description: '删除问题',
                code: [102505, 102506],
                id: 102505
            }, ]
        }, {
            name: '病症管理',
            description: '病症管理',
            code: 101400,
            id: 101400,
            authorities: [{
                name: '新增',
                description: '新增病症',
                code: [101401],
                id: 101401
            }, {
                name: '查看',
                description: '查看病症',
                code: [101402, 101403],
                id: 101402
            }, {
                name: '编辑',
                description: '编辑病症',
                code: [101404],
                id: 101404
            }, {
                name: '删除',
                description: '删除病症',
                code: [101405, 101406],
                id: 101405
            }, ]
        }, {
            name: '优秀案例管理',
            description: '优秀案例管理',
            code: 101900,
            id: 101900,
            authorities: [{
                name: '新增',
                description: '新增优秀案例',
                code: [101901],
                id: 101901
            }, {
                name: '查看',
                description: '查看优秀案例',
                code: [101902, 101903],
                id: 101902
            }, {
                name: '编辑',
                description: '编辑优秀案例',
                code: [101904],
                id: 101904
            }, {
                name: '删除',
                description: '删除优秀案例',
                code: [101905, 101906],
                id: 101905
            }, ]
        }, {
            name: '诊断数据',
            description: '诊断数据管理',
            code: 100900,
            id: 100900,
            authorities: [{
                name: '查看',
                description: '查看诊断数据',
                code: [100901, 100902],
                id: 100901
            }, ]
        }, {
            name: '诊疗方案管理',
            description: '诊疗方案管理',
            code: 101000,
            id: 101000,
            authorities: [{
                name: '新增',
                description: '新增诊疗方案',
                code: [101001],
                id: 101001
            }, {
                name: '删除',
                description: '查看诊疗方案',
                code: [101002],
                id: 101002
            }, {
                name: '编辑',
                description: '编辑诊疗方案',
                code: [101003],
                id: 101003
            }, {
                name: '查看',
                description: '删除诊疗方案',
                code: [101004, 101005],
                id: 101004
            }, ]
        }, {
            name: '养生资讯管理',
            description: '养生资讯管理',
            code: 101100,
            id: 101100,
            authorities: [{
                name: '新增',
                description: '新增养生资讯',
                code: [101101],
                id: 101101
            }, {
                name: '删除',
                description: '删除养生资讯',
                code: [101102, 101106],
                id: 101102
            }, {
                name: '编辑',
                description: '编辑养生资讯',
                code: [101103],
                id: 101103
            }, {
                name: '查看',
                description: '查看养生资讯',
                code: [101104, 101105],
                id: 101104
            }, {
                name: '推荐',
                description: '推荐养生资讯',
                code: [101107],
                id: 101107
            }, {
                name: '置顶',
                description: '置顶养生资讯',
                code: [101108],
                id: 101108
            }, ]
        }, {
            name: '穴位管理',
            description: '穴位管理',
            code: 101200,
            id: 101200,
            authorities: [{
                name: '新增',
                description: '新增穴位',
                code: [101201],
                id: 101201
            }, {
                name: '删除',
                description: '删除穴位',
                code: [101202, 101206],
                id: 101202
            }, {
                name: '编辑',
                description: '编辑穴位',
                code: [101203],
                id: 101203
            }, {
                name: '查看',
                description: '查看穴位',
                code: [101204, 101205],
                id: 101204
            }, ]
        }, {
            name: '经络管理',
            description: '经络管理',
            code: 101300,
            id: 101300,
            authorities: [{
                name: '新增',
                description: '新增经络',
                code: [101301],
                id: 101301
            }, {
                name: '删除',
                description: '删除经络',
                code: [101302, 101306],
                id: 101302
            }, {
                name: '编辑',
                description: '编辑经络',
                code: [101303],
                id: 101303
            }, {
                name: '查看',
                description: '查看经络',
                code: [101304, 101305],
                id: 101304
            }, ]
        }, {
            name: '文件管理',
            description: '文件管理',
            code: 101500,
            id: 101500,
            authorities: [{
                name: '新增',
                description: '上传文件',
                code: [101501],
                id: 101501
            }, {
                name: '修改',
                description: '修改文件',
                code: [101502],
                id: 101502
            }, ]
        }, {
            name: '文章分类管理',
            description: '文章分类管理',
            code: 101600,
            id: 101600,
            authorities: [{
                name: '新增',
                description: '新增文章分类',
                code: [101601],
                id: 101601
            }, {
                name: '删除',
                description: '删除文章分类',
                code: [101602],
                id: 101602
            }, {
                name: '编辑',
                description: '编辑文章分类',
                code: [101603],
                id: 101603
            }, {
                name: '查看',
                description: '查看文章分类',
                code: [101604, 101605],
                id: 101604
            }, {
                name: '移动',
                description: '移动文章分类',
                code: [101606],
                id: 101606
            }, ]
        }, {
            name: '数据明细',
            description: '数据明细',
            code: 101800,
            id: 101800,
            authorities: [{
                name: '查看',
                description: '查看数据明细',
                code: [101801],
                id: 101801
            }, ]
        }, {
            name: '诊断结论',
            description: '诊断结论',
            code: 102100,
            id: 102100,
            authorities: [{
                name: '查看',
                description: '查看诊断结论',
                code: [102101],
                id: 102101
            }, ]
        }, {
            name: '诊断报告',
            description: '诊断报告',
            code: 102000,
            id: 102000,
            authorities: [{
                name: '查看',
                description: '查看诊断报告',
                code: [102001],
                id: 102001
            }, ]
        }, {
            name: '匹配方案',
            description: '匹配方案',
            code: 102300,
            id: 102300,
            authorities: [{
                name: '查看',
                description: '查看匹配方案',
                code: [102301],
                id: 102301
            }, {
                name: '修改',
                description: '修改匹配方案',
                code: [102302],
                id: 102302
            }, ]
        },
        {
            name: '推荐模块',
            description: '推荐模块',
            code: 105900,
            id: 105900,
            authorities: [{
                    name: '查看',
                    description: '查看推荐记录',
                    code: [105901],
                    id: 105901
                },
                {
                    name: '删除',
                    description: '删除推荐记录',
                    code: [105902, 105903],
                    id: 105902
                }
            ]
        },
        {
            name: '版本更新模块',
            description: '版本更新模块',
            code: 106000,
            id: 106000,
            authorities: [{
                    name: '新增',
                    description: '新增版本',
                    code: [106001],
                    id: 106001
                },
                {
                    name: '查看',
                    description: '查看版本',
                    code: [106002],
                    id: 106002
                },
                {
                    name: '删除',
                    description: '删除版本',
                    code: [106003, 106004],
                    id: 106003
                }
            ]
        }, {
            name: '意见反馈',
            description: '意见反馈',
            code: 102400,
            id: 102400,
            authorities: [{
                name: '新增',
                description: '新增意见反馈',
                code: [102401],
                id: 102401
            }, ]
        }, {
            name: '省市管理',
            description: '省市管理',
            code: 107500,
            id: 107500,
            authorities: [{
                name: '新增',
                description: '新增省市',
                code: [107501],
                id: 107501
            }, {
                name: '删除',
                description: '删除省市',
                code: [107502],
                id: 107502
            }, {
                name: '编辑',
                description: '编辑省市',
                code: [107503],
                id: 107503
            }, {
                name: '查看',
                description: '查看省市',
                code: [107504, 107505],
                id: 107504
            }, {
                name: '移动',
                description: '移动省市',
                code: [107506],
                id: 107506
            }, ]
        },
    ]
};